=== togramort/BSULabs/web/recording_parsing/src/main/java/compositions/xml/compositions.xsd
<?xml version="1.0"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.bsu.by"
        xmlns="http://www.bsu.by"
        elementFormDefault="qualified">

    <xs:simpleType name="Compositions" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Concert"/>
            <xs:enumeration value="Opera"/>
            <xs:enumeration value="Romance"/>
            <xs:enumeration value="Sonata"/>
            <xs:enumeration value="Song"/>
            <xs:enumeration value="Symphony"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Fields" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Name"/>
            <xs:enumeration value="Duration"/>
            <xs:enumeration value="Composer"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AbstractComposition" abstract="true">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="duration" type="xs:int"/>
            <xs:element name="composer" type="xs:string"/>
            <xs:element name="performers" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="VocalComposition" abstract="true">
        <xs:complexContent>
            <xs:extension base="AbstractComposition">
                <xs:sequence>
                    <xs:element name="textWriter" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="InstrumentalComposition" abstract="true">
        <xs:complexContent>
            <xs:extension base="AbstractComposition">
                <xs:sequence>
                    <xs:element name="tonality" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Concert">
        <xs:complexContent>
            <xs:extension base="InstrumentalComposition">
                <xs:sequence>
                    <xs:element name="instrument" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Sonata">
        <xs:complexContent>
            <xs:extension base="InstrumentalComposition"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Symphony">
        <xs:complexContent>
            <xs:extension base="InstrumentalComposition"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Opera">
        <xs:complexContent>
            <xs:extension base="VocalComposition"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Romance">
        <xs:complexContent>
            <xs:extension base="VocalComposition"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Song">
        <xs:complexContent>
            <xs:extension base="VocalComposition">
                <xs:sequence>
                    <xs:element name="genre" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Disk">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element name="concert" type="Concert"/>
                    <xs:element name="sonata" type="Sonata"/>
                    <xs:element name="symphony" type="Symphony"/>
                    <xs:element name="opera" type="Opera"/>
                    <xs:element name="romance" type="Romance"/>
                    <xs:element name="song" type="Song"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== togramort/BSULabs/web/recording_parsing/src/main/java/compositions/xml/disk.xml
<Disk
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.bsu.by"
        xsi:schemaLocation="http://www.bsu.by compositions.xsd">

    <opera>
        <name>Ruslan and Ludmila</name>
        <duration>3</duration>
        <composer>Beethoven</composer>
        <performers>Beethoven</performers>
        <textWriter>Pushkin</textWriter>
    </opera>

    <opera>
        <name>Duke Igor</name>
        <duration>3</duration>
        <composer>Borodin</composer>
        <performers>Borodin</performers>
        <textWriter>unknown</textWriter>
    </opera>

    <romance>
        <name>Summer time</name>
        <duration>15</duration>
        <composer>Blocking</composer>
        <performers>Bah</performers>
        <textWriter>Pushkin</textWriter>
    </romance>

    <romance>
        <name>Dead inside</name>
        <duration>11</duration>
        <composer>Concurrent</composer>
        <performers>Borodin</performers>
        <textWriter>unknown</textWriter>
    </romance>

    <song>
        <name>Autumn</name>
        <duration>2</duration>
        <composer>Bread</composer>
        <performers>Bulka</performers>
        <textWriter>Sunshine</textWriter>
        <genre>pop</genre>
    </song>

    <song>
        <name>float</name>
        <duration>4</duration>
        <composer>Kudal</composer>
        <performers>Ludah</performers>
        <textWriter>Varona</textWriter>
        <genre>rock</genre>
    </song>

    <concert>
        <name>Great concert</name>
        <duration>100</duration>
        <composer>Grodenka</composer>
        <performers>Ludah</performers>
        <tonality>C dur</tonality>
        <instrument>rock</instrument>
    </concert>

    <sonata>
        <name>Dark side</name>
        <duration>17</duration>
        <composer>Malina</composer>
        <performers>E moll</performers>
        <tonality>Soroka</tonality>
    </sonata>


</Disk>
